"use client";

import { useState, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import {
    Send, Loader2, RefreshCw, User,
    ChevronLeft, Sparkles, PanelLeftClose, PanelLeftOpen,
    MessageSquare, Activity, Shield, Building2
} from "lucide-react";
import { useContextStore } from "@/stores/context-store";
import { format } from "date-fns";
import { toast } from "sonner";
import { DateRangePicker } from "./date-range-picker";
import { Badge } from "@/components/ui/badge";

interface Message {
    id: string;
    sender: 'guest' | 'admin';
    text: string;
    time: string;
}

interface SimulatedConversation {
    id: string;
    guestName: string;
    lastMessage: string;
    status: 'needs_reply' | 'resolved';
    messages: Message[];
}

export function GuestChatInterface() {
    const {
        contextType,
        propertyId,
        propertyName,
        dateRange,
        setDateRange,
        setConversationSummary,
        conversationSummary
    } = useContextStore();

    const [activeConversationId, setActiveConversationId] = useState<string | null>(null);
    const [replyText, setReplyText] = useState("");
    const [conversations, setConversations] = useState<SimulatedConversation[]>([]);
    const [isSuggesting, setIsSuggesting] = useState(false);
    const [isGeneratingSummary, setIsGeneratingSummary] = useState(false);
    const [isInboxCollapsed, setIsInboxCollapsed] = useState(false);
    const [isLoading, setIsLoading] = useState(false);

    const fetchConversations = async (showLoadingToast = false) => {
        if (!propertyId || !dateRange?.from || !dateRange?.to) return;

        if (showLoadingToast) toast.loading("Fetching conversations...", { id: "fetch_conv" });

        const from = format(dateRange.from, 'yyyy-MM-dd');
        const to = format(dateRange.to, 'yyyy-MM-dd');

        try {
            // Load cached conversations
            const convRes = await fetch(`/api/hostaway/conversations/cached?listingId=${propertyId}&from=${from}&to=${to}`);
            if (convRes.ok) {
                const convData = await convRes.json();
                setConversations(convData.conversations || []);
                if (showLoadingToast) toast.success(`Loaded ${convData.conversations?.length || 0} active threads`, { id: "fetch_conv" });
            }

            // Load cached summary
            const sumRes = await fetch(`/api/hostaway/summary?listingId=${propertyId}&from=${from}&to=${to}`);
            if (sumRes.ok) {
                const sumData = await sumRes.json();
                if (sumData.summary) setConversationSummary(sumData.summary);
            }
        } catch (e) {
            console.warn("Failed to load cached conversations", e);
            if (showLoadingToast) toast.error("Failed to load conversations", { id: "fetch_conv" });
        }
    };

    useEffect(() => {
        setConversations([]);
        setActiveConversationId(null);
        setConversationSummary(null);
        setReplyText("");
        fetchConversations();
    }, [propertyId, dateRange?.from?.getTime(), dateRange?.to?.getTime()]);

    const handleAiSuggest = async () => {
        if (!activeConversationId) return;
        const conversation = conversations.find(c => c.id === activeConversationId);
        if (!conversation) return;

        setIsSuggesting(true);
        try {
            const lastGuestMessage = [...conversation.messages].reverse().find(m => m.sender === 'guest')?.text || "";

            toast.loading("Agent is thinking of a reply...", { id: 'suggest' });

            const res = await fetch("/api/hostaway/suggest-reply", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    message: lastGuestMessage,
                    guestName: conversation.guestName,
                    propertyName: propertyName || "Our Property",
                })
            });

            const data = await res.json();
            let suggestedText = "";

            if (res.ok && data.reply) {
                suggestedText = data.reply;
            } else {
                // Fallback
                await new Promise(r => setTimeout(r, 1500));
                suggestedText = `Hi ${conversation.guestName}, thanks for reaching out! I'd be happy to help with that.`;
            }

            setReplyText(suggestedText);
            toast.success("Response generated by Agent", { id: 'suggest' });
        } catch (e) {
            toast.error("Failed to get Agent suggestion", { id: 'suggest' });
        } finally {
            setIsSuggesting(false);
        }
    };

    const handleSendReply = async () => {
        if (!replyText.trim() || !activeConversationId) return;
        const textToSave = replyText;
        const convId = activeConversationId;
        setReplyText("");

        try {
            const res = await fetch("/api/hostaway/reply", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ conversationId: convId, text: textToSave })
            });

            if (!res.ok) throw new Error("Failed to save to DB");

            setConversations(prev => prev.map(conv => {
                if (conv.id === convId) {
                    return {
                        ...conv,
                        status: 'resolved' as const,
                        lastMessage: textToSave,
                        messages: [
                            ...conv.messages,
                            { id: Date.now().toString(), sender: 'admin' as const, text: textToSave, time: "Just now" }
                        ]
                    };
                }
                return conv;
            }));

            toast.success("Reply securely saved to shadow database", { id: 'reply' });
        } catch (error) {
            setReplyText(textToSave);
            toast.error("Failed to save shadow reply", { id: 'reply' });
        }
    };

    const activeConversation = conversations.find(c => c.id === activeConversationId);

    if (contextType === "portfolio") {
        return (
            <div className="flex flex-col flex-1 items-center justify-center h-full text-muted-foreground p-8 text-center bg-muted/5">
                <Building2 className="h-16 w-16 mb-6 opacity-10" />
                <h3 className="text-xl font-bold text-foreground">Select a Property</h3>
                <p className="mt-2 text-sm max-w-sm">
                    Please select a property from the sidebar to view guest conversations and use the AI Inbox Analyst.
                </p>
            </div>
        );
    }

    return (
        <div className="flex flex-col flex-1 overflow-hidden h-full">
            {/* Standard Header */}
            <div className="border-b bg-background flex flex-col shrink-0 relative z-10 shadow-sm">
                <div className="flex flex-wrap items-center justify-between px-6 py-4 gap-4">
                    <div className="flex items-center gap-3">
                        <div className="rounded-lg bg-emerald-500/10 p-2">
                            <MessageSquare className="h-5 w-5 text-emerald-600" />
                        </div>
                        <div>
                            <h3 className="text-lg font-black tracking-tight">
                                Guest Inbox
                            </h3>
                            <p className="text-xs font-bold text-muted-foreground uppercase tracking-widest">
                                {propertyName || "Property Communications"}
                            </p>
                        </div>
                    </div>

                    <div className="flex items-center gap-2">
                        <div id="tour-date-range" className="bg-muted/30 p-1 rounded-xl border border-border/50">
                            <DateRangePicker
                                date={dateRange}
                                setDate={(newRange) => {
                                    setDateRange(newRange);
                                }}
                            />
                        </div>
                        <div className="hidden sm:block h-6 w-px bg-border/50 mx-1" />
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={async () => {
                                if (!dateRange?.from || !dateRange?.to || !propertyId) return;
                                setIsGeneratingSummary(true);
                                try {
                                    toast.loading("AI is generating summary...", { id: 'summary' });
                                    const from = format(dateRange.from, 'yyyy-MM-dd');
                                    const to = format(dateRange.to, 'yyyy-MM-dd');
                                    const res = await fetch(`/api/hostaway/summary`, {
                                        method: "POST",
                                        headers: { "Content-Type": "application/json" },
                                        body: JSON.stringify({ listingId: propertyId, dateFrom: from, dateTo: to })
                                    });
                                    if (res.ok) {
                                        const data = await res.json();
                                        setConversationSummary(data.summary);
                                        toast.success("Summary generated & saved!", { id: 'summary' });
                                    } else {
                                        throw new Error("Failed");
                                    }
                                } catch (e) {
                                    toast.error("Failed to generate summary", { id: 'summary' });
                                } finally {
                                    setIsGeneratingSummary(false);
                                }
                            }}
                            disabled={!dateRange?.from || !dateRange?.to || isGeneratingSummary || conversations.length === 0}
                            className="h-9 gap-2 bg-background hover:bg-background/80 border-border/50 font-bold shadow-sm text-violet-600 border-violet-500/30"
                        >
                            {isGeneratingSummary ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
                            <span className="hidden sm:inline">{isGeneratingSummary ? 'Generating...' : 'Generate Summary'}</span>
                        </Button>
                    </div>
                </div>
            </div>

            <div className="flex-1 flex overflow-hidden">
                {/* Guest Inbox Sidebar — collapsible */}
                <div className={`border-r bg-muted/10 flex flex-col border-border/50 transition-all duration-200 ${isInboxCollapsed ? 'w-0 overflow-hidden border-r-0' : activeConversationId ? 'hidden md:flex w-1/3' : 'flex w-1/3'}`}>
                    <div className="p-4 border-b bg-background border-border/50 flex items-center justify-between">
                        <h3 className="font-black uppercase tracking-widest text-xs text-muted-foreground">Guest Inbox</h3>
                        <div className="flex items-center gap-1">
                            <Button
                                variant="ghost"
                                size="icon"
                                className="h-7 w-7 rounded-full hover:bg-muted"
                                onClick={() => fetchConversations(true)}
                                disabled={isLoading || !propertyId}
                            >
                                <RefreshCw className="h-3.5 w-3.5 text-muted-foreground" />
                            </Button>
                            <Button
                                variant="ghost"
                                size="icon"
                                className="h-7 w-7 rounded-full hover:bg-muted"
                                onClick={() => setIsInboxCollapsed(true)}
                            >
                                <PanelLeftClose className="h-3.5 w-3.5 text-muted-foreground" />
                            </Button>
                        </div>
                    </div>

                    <div className="flex-1 overflow-y-auto p-4 space-y-2">
                        {conversations.map(conv => (
                            <button
                                key={conv.id}
                                onClick={() => setActiveConversationId(conv.id)}
                                className={`w-full text-left p-3 rounded-xl transition-all border ${activeConversationId === conv.id ? 'bg-primary/5 border-primary/30' : 'bg-background hover:bg-muted/50 border-border/50 hover:border-border'}`}
                            >
                                <div className="flex items-start gap-3">
                                    <div className="h-8 w-8 rounded-full bg-muted flex items-center justify-center shrink-0">
                                        <User className="h-4 w-4 text-muted-foreground" />
                                    </div>
                                    <div className="flex flex-col min-w-0 flex-1">
                                        <div className="flex items-center justify-between">
                                            <span className="text-sm font-bold truncate">{conv.guestName}</span>
                                            {conv.status === 'needs_reply' && <div className="h-2 w-2 rounded-full bg-amber-500" />}
                                        </div>
                                        <span className="text-xs text-muted-foreground truncate font-medium mt-0.5">{conv.lastMessage}</span>
                                    </div>
                                </div>
                            </button>
                        ))}
                        {conversations.length === 0 && (
                            <div className="text-center py-8 text-muted-foreground">
                                <User className="h-8 w-8 mx-auto mb-2 opacity-20" />
                                <p className="text-xs font-medium">No conversations</p>
                                <p className="text-[10px] mt-1 text-center px-4">No activity in this date range.<br />Sync from Dashboard if needed.</p>
                            </div>
                        )}
                    </div>
                </div>

                {/* Expand button when inbox is collapsed */}
                {isInboxCollapsed && (
                    <div className="flex flex-col items-center py-3 px-1 border-r border-border/50 bg-muted/10">
                        <Button
                            variant="ghost"
                            size="icon"
                            className="h-7 w-7 rounded-full hover:bg-muted"
                            onClick={() => setIsInboxCollapsed(false)}
                        >
                            <PanelLeftOpen className="h-3.5 w-3.5 text-slate-400" />
                        </Button>
                    </div>
                )}

                <div className={`flex-1 flex flex-col bg-background relative ${!activeConversationId ? 'hidden md:flex' : 'flex'}`}>
                    {activeConversation ? (
                        <>
                            <div className="flex items-center p-4 border-b border-border/50 bg-background shadow-sm z-10">
                                <div className="flex items-center gap-3">
                                    <Button
                                        variant="ghost"
                                        size="icon"
                                        className="h-8 w-8 -ml-2 rounded-full hover:bg-muted md:hidden"
                                        onClick={() => setActiveConversationId(null)}
                                    >
                                        <ChevronLeft className="h-4 w-4" />
                                    </Button>
                                    <div className="flex flex-col">
                                        <span className="text-sm font-bold leading-none">{activeConversation.guestName}</span>
                                        <span className="text-[10px] text-muted-foreground uppercase font-black tracking-widest mt-1">Hostaway Guest</span>
                                    </div>
                                </div>
                            </div>
                            <div className="flex-1 overflow-y-auto p-6 space-y-4">
                                {activeConversation.messages.map((msg) => (
                                    <div key={msg.id} className={`flex flex-col max-w-[85%] ${msg.sender === 'admin' ? 'ml-auto items-end' : 'mr-auto items-start'}`}>
                                        <div className={`px-4 py-2.5 rounded-2xl overflow-hidden ${msg.sender === 'admin' ? 'bg-primary text-primary-foreground rounded-br-sm' : 'bg-muted border border-border/50 rounded-bl-sm'}`}>
                                            <p className="text-sm leading-relaxed whitespace-pre-wrap break-words">{msg.text}</p>
                                        </div>
                                        <span className="text-[9px] font-bold text-muted-foreground mt-1 px-1 tracking-wider uppercase">{msg.time}</span>
                                    </div>
                                ))}
                            </div>

                            {/* Conversation Summary Sidebar/Overlay for Tablet+ */}
                            {conversationSummary && (
                                <div className="absolute top-20 right-6 w-64 bg-background/80 backdrop-blur-md border border-border shadow-2xl rounded-2xl p-4 hidden xl:block z-20">
                                    <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-violet-600 mb-2">AI Summary</h4>
                                    <p className="text-[11px] text-muted-foreground leading-relaxed italic line-clamp-6">
                                        "{conversationSummary}"
                                    </p>
                                </div>
                            )}

                            <div className="p-4 bg-background border-t border-border/50 shrink-0 relative z-10">
                                <div className="flex items-center gap-2">
                                    <div className="relative flex-1 flex items-center">
                                        <input
                                            type="text"
                                            value={replyText}
                                            onChange={(e) => setReplyText(e.target.value)}
                                            onKeyDown={(e) => { if (e.key === 'Enter') handleSendReply(); }}
                                            placeholder={`Reply to ${activeConversation.guestName}...`}
                                            className="w-full bg-muted/50 border border-border/50 rounded-full pl-4 pr-10 h-10 text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all font-medium placeholder:font-normal"
                                        />
                                        <Button
                                            variant="ghost"
                                            size="icon"
                                            onClick={handleAiSuggest}
                                            disabled={isSuggesting}
                                            className={`absolute right-1.5 h-7 w-7 rounded-full transition-all ${isSuggesting ? 'text-amber-500' : 'text-muted-foreground hover:text-amber-500 hover:bg-amber-50'}`}
                                        >
                                            {isSuggesting ? (
                                                <Loader2 className="h-3.5 w-3.5 animate-spin" />
                                            ) : (
                                                <Sparkles className="h-3.5 w-3.5" />
                                            )}
                                        </Button>
                                    </div>
                                    <Button
                                        size="icon"
                                        onClick={handleSendReply}
                                        disabled={!replyText.trim()}
                                        className="h-10 w-10 rounded-full shrink-0 shadow-md"
                                    >
                                        <Send className="h-4 w-4" />
                                    </Button>
                                </div>
                                <p className="text-[9px] text-center text-muted-foreground/50 mt-2 font-bold uppercase tracking-widest">
                                    Sending securely via shadow database
                                </p>
                            </div>
                        </>
                    ) : (
                        <div className="flex-1 flex flex-col items-center justify-center text-muted-foreground">
                            <User className="h-12 w-12 mb-4 opacity-10" />
                            <p className="text-sm font-medium">No conversation selected</p>
                            <p className="text-xs mt-1">Select a guest from the list to view or reply.</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
