/**
 * Sample listings seed data — 5 Dubai properties.
 * These are used for testing when no real Hostaway import has been done.
 * orgId is filled in at seed-time from the first Organization document.
 */
export const SAMPLE_LISTINGS_SEED = [
  {
    hostawayId: "HA_10001",
    name: "Marina Heights 1BR",
    city: "Dubai",
    countryCode: "AE",
    area: "Dubai Marina",
    bedroomsNumber: 1,
    bathroomsNumber: 1,
    propertyTypeId: 1,
    price: 650,
    currencyCode: "AED",
    personCapacity: 2,
    address: "Marina Gate Tower 1, Dubai Marina",
    priceFloor: 350,
    priceCeiling: 1800,
    guardrailsSource: "manual",
    lastMinuteEnabled: true,
    lastMinuteDaysOut: 7,
    lastMinuteDiscountPct: 15,
    farOutEnabled: true,
    farOutDaysOut: 90,
    farOutMarkupPct: 10,
    dowPricingEnabled: true,
    dowDays: [3, 4], // Thu+Fri (0=Mon)
    dowPriceAdjPct: 20,
    gapPreventionEnabled: true,
    minFragmentThreshold: 2,
    gapFillEnabled: true,
    gapFillLengthMin: 1,
    gapFillLengthMax: 3,
    gapFillDiscountPct: 12,
    amenities: ["WiFi", "Pool", "Gym", "Parking", "Sea View", "Balcony"],
    isActive: true,
  },
  {
    hostawayId: "HA_10002",
    name: "Downtown Residences 2BR",
    city: "Dubai",
    countryCode: "AE",
    area: "Downtown Dubai",
    bedroomsNumber: 2,
    bathroomsNumber: 2,
    propertyTypeId: 1,
    price: 950,
    currencyCode: "AED",
    personCapacity: 4,
    address: "Burj Crown, Downtown Dubai",
    priceFloor: 550,
    priceCeiling: 2800,
    guardrailsSource: "manual",
    lastMinuteEnabled: true,
    lastMinuteDaysOut: 5,
    lastMinuteDiscountPct: 12,
    farOutEnabled: true,
    farOutDaysOut: 60,
    farOutMarkupPct: 8,
    dowPricingEnabled: true,
    dowDays: [3, 4],
    dowPriceAdjPct: 25,
    gapPreventionEnabled: true,
    minFragmentThreshold: 2,
    gapFillEnabled: false,
    gapFillLengthMin: 1,
    gapFillLengthMax: 2,
    gapFillDiscountPct: 10,
    amenities: ["WiFi", "Pool", "Gym", "Concierge", "Burj Khalifa View", "Balcony"],
    isActive: true,
  },
  {
    hostawayId: "HA_10003",
    name: "JBR Beach Studio",
    city: "Dubai",
    countryCode: "AE",
    area: "Jumeirah Beach Residence",
    bedroomsNumber: 0,
    bathroomsNumber: 1,
    propertyTypeId: 1,
    price: 420,
    currencyCode: "AED",
    personCapacity: 2,
    address: "Shams 4, JBR, Dubai",
    priceFloor: 220,
    priceCeiling: 1100,
    guardrailsSource: "manual",
    lastMinuteEnabled: true,
    lastMinuteDaysOut: 10,
    lastMinuteDiscountPct: 18,
    farOutEnabled: false,
    farOutDaysOut: 90,
    farOutMarkupPct: 5,
    dowPricingEnabled: true,
    dowDays: [3, 4],
    dowPriceAdjPct: 15,
    gapPreventionEnabled: true,
    minFragmentThreshold: 3,
    gapFillEnabled: true,
    gapFillLengthMin: 1,
    gapFillLengthMax: 2,
    gapFillDiscountPct: 15,
    amenities: ["WiFi", "Beach Access", "Pool", "Walk to JBR Walk"],
    isActive: true,
  },
  {
    hostawayId: "HA_10004",
    name: "Palm Villa 3BR",
    city: "Dubai",
    countryCode: "AE",
    area: "Palm Jumeirah",
    bedroomsNumber: 3,
    bathroomsNumber: 3,
    propertyTypeId: 2,
    price: 2200,
    currencyCode: "AED",
    personCapacity: 6,
    address: "Frond N, Palm Jumeirah, Dubai",
    priceFloor: 1200,
    priceCeiling: 6000,
    guardrailsSource: "ai",
    lastMinuteEnabled: false,
    lastMinuteDaysOut: 7,
    lastMinuteDiscountPct: 10,
    farOutEnabled: true,
    farOutDaysOut: 120,
    farOutMarkupPct: 15,
    dowPricingEnabled: true,
    dowDays: [3, 4, 5], // Thu+Fri+Sat
    dowPriceAdjPct: 30,
    gapPreventionEnabled: true,
    minFragmentThreshold: 4,
    gapFillEnabled: false,
    gapFillLengthMin: 2,
    gapFillLengthMax: 4,
    gapFillDiscountPct: 8,
    amenities: ["Private Pool", "Beach Access", "WiFi", "BBQ", "5BR capacity", "Sea View", "Parking x3"],
    isActive: true,
  },
  {
    hostawayId: "HA_10005",
    name: "Bay View 1BR",
    city: "Dubai",
    countryCode: "AE",
    area: "Business Bay",
    bedroomsNumber: 1,
    bathroomsNumber: 1,
    propertyTypeId: 1,
    price: 580,
    currencyCode: "AED",
    personCapacity: 2,
    address: "Damac Maison, Business Bay, Dubai",
    priceFloor: 300,
    priceCeiling: 1500,
    guardrailsSource: "manual",
    lastMinuteEnabled: true,
    lastMinuteDaysOut: 7,
    lastMinuteDiscountPct: 15,
    farOutEnabled: true,
    farOutDaysOut: 90,
    farOutMarkupPct: 10,
    dowPricingEnabled: true,
    dowDays: [3, 4],
    dowPriceAdjPct: 18,
    gapPreventionEnabled: true,
    minFragmentThreshold: 2,
    gapFillEnabled: true,
    gapFillLengthMin: 1,
    gapFillLengthMax: 3,
    gapFillDiscountPct: 12,
    amenities: ["WiFi", "Pool", "Gym", "Canal View", "Metro Access"],
    isActive: true,
  },
];
