export const MARKET_TEMPLATES_SEED = [
  {
    marketCode: "UAE_DXB",
    displayName: "Dubai, UAE",
    country: "United Arab Emirates",
    currency: "AED",
    timezone: "Asia/Dubai",
    weekendDefinition: "thu_fri",
    flag: "🇦🇪",
    guardrailDefaults: {
      maxSingleDayChangePct: 15,
      autoApproveThreshold: 5,
      absoluteFloorMultiplier: 0.5,
      absoluteCeilingMultiplier: 3.0,
    },
    seasonalPatterns: [
      { month: 1, demandScore: 92, ratePremiumPct: 25, notes: "Peak winter — Dubai Shopping Festival" },
      { month: 2, demandScore: 88, ratePremiumPct: 20, notes: "Dubai Shopping Festival end" },
      { month: 3, demandScore: 75, ratePremiumPct: 10, notes: "Ramadan season" },
      { month: 4, demandScore: 55, ratePremiumPct: -5, notes: "Heat begins" },
      { month: 5, demandScore: 40, ratePremiumPct: -15, notes: "Low season" },
      { month: 6, demandScore: 30, ratePremiumPct: -25, notes: "Peak heat" },
      { month: 7, demandScore: 28, ratePremiumPct: -28, notes: "Peak heat" },
      { month: 8, demandScore: 32, ratePremiumPct: -22, notes: "Summer families" },
      { month: 9, demandScore: 55, ratePremiumPct: -5, notes: "Recovery" },
      { month: 10, demandScore: 75, ratePremiumPct: 12, notes: "Good season" },
      { month: 11, demandScore: 88, ratePremiumPct: 22, notes: "Ideal season" },
      { month: 12, demandScore: 95, ratePremiumPct: 28, notes: "F1 Abu Dhabi + New Year" },
    ],
    eventApiConfig: {
      ticketmasterCity: "Dubai",
      eventbriteCity: "Dubai",
      customKeywords: ["Dubai Shopping Festival", "F1 Abu Dhabi", "Ramadan", "UAE National Day"],
    },
    regulatoryFlags: {
      hasNightCap: false,
      nightCapPerYear: undefined,
      requiresLicence: true,
      licenceFieldLabel: "Dubai Tourism Permit Number",
    },
    isActive: true,
  },
  {
    marketCode: "GBR_LON",
    displayName: "London, UK",
    country: "United Kingdom",
    currency: "GBP",
    timezone: "Europe/London",
    weekendDefinition: "fri_sat",
    flag: "🇬🇧",
    guardrailDefaults: {
      maxSingleDayChangePct: 10,
      autoApproveThreshold: 3,
      absoluteFloorMultiplier: 0.5,
      absoluteCeilingMultiplier: 2.5,
    },
    seasonalPatterns: [
      { month: 1, demandScore: 45, ratePremiumPct: -15, notes: "Post-Christmas lull" },
      { month: 2, demandScore: 48, ratePremiumPct: -12 },
      { month: 3, demandScore: 60, ratePremiumPct: 0, notes: "Spring begins" },
      { month: 4, demandScore: 72, ratePremiumPct: 10, notes: "Easter + spring break" },
      { month: 5, demandScore: 78, ratePremiumPct: 15, notes: "Bank holidays" },
      { month: 6, demandScore: 85, ratePremiumPct: 22, notes: "Summer begins" },
      { month: 7, demandScore: 92, ratePremiumPct: 30, notes: "Peak summer / school hols" },
      { month: 8, demandScore: 88, ratePremiumPct: 25, notes: "School holidays" },
      { month: 9, demandScore: 75, ratePremiumPct: 12, notes: "Events season" },
      { month: 10, demandScore: 65, ratePremiumPct: 5, notes: "Autumn" },
      { month: 11, demandScore: 50, ratePremiumPct: -8 },
      { month: 12, demandScore: 70, ratePremiumPct: 18, notes: "Christmas + NYE" },
    ],
    eventApiConfig: {
      ticketmasterCity: "London",
      eventbriteCity: "London",
      customKeywords: ["Wimbledon", "Chelsea Flower Show", "London Marathon", "NYE London"],
    },
    regulatoryFlags: {
      hasNightCap: true,
      nightCapPerYear: 90,
      requiresLicence: false,
    },
    isActive: true,
  },
  {
    marketCode: "USA_NYC",
    displayName: "New York, USA",
    country: "United States",
    currency: "USD",
    timezone: "America/New_York",
    weekendDefinition: "fri_sat",
    flag: "🇺🇸",
    guardrailDefaults: {
      maxSingleDayChangePct: 12,
      autoApproveThreshold: 4,
      absoluteFloorMultiplier: 0.55,
      absoluteCeilingMultiplier: 2.8,
    },
    seasonalPatterns: [
      { month: 1, demandScore: 55, ratePremiumPct: -5 },
      { month: 2, demandScore: 58, ratePremiumPct: -2 },
      { month: 3, demandScore: 65, ratePremiumPct: 8 },
      { month: 4, demandScore: 78, ratePremiumPct: 18, notes: "Spring break" },
      { month: 5, demandScore: 82, ratePremiumPct: 22 },
      { month: 6, demandScore: 85, ratePremiumPct: 25 },
      { month: 7, demandScore: 80, ratePremiumPct: 20 },
      { month: 8, demandScore: 78, ratePremiumPct: 18 },
      { month: 9, demandScore: 82, ratePremiumPct: 22, notes: "Fashion Week" },
      { month: 10, demandScore: 85, ratePremiumPct: 25, notes: "Fall foliage" },
      { month: 11, demandScore: 72, ratePremiumPct: 12, notes: "Thanksgiving" },
      { month: 12, demandScore: 75, ratePremiumPct: 15, notes: "Holiday season" },
    ],
    eventApiConfig: {
      ticketmasterCity: "New York",
      eventbriteCity: "New York",
      customKeywords: ["NYC Marathon", "New Year's Eve Times Square", "Fashion Week", "US Open"],
    },
    regulatoryFlags: {
      hasNightCap: false,
      requiresLicence: true,
      licenceFieldLabel: "NYC STR Permit Number",
    },
    isActive: true,
  },
  {
    marketCode: "FRA_PAR",
    displayName: "Paris, France",
    country: "France",
    currency: "EUR",
    timezone: "Europe/Paris",
    weekendDefinition: "fri_sat",
    flag: "🇫🇷",
    guardrailDefaults: {
      maxSingleDayChangePct: 10,
      autoApproveThreshold: 3,
      absoluteFloorMultiplier: 0.5,
      absoluteCeilingMultiplier: 2.5,
    },
    seasonalPatterns: [
      { month: 1, demandScore: 52, ratePremiumPct: -8 },
      { month: 2, demandScore: 58, ratePremiumPct: -3 },
      { month: 3, demandScore: 68, ratePremiumPct: 8 },
      { month: 4, demandScore: 80, ratePremiumPct: 20, notes: "Spring / Easter" },
      { month: 5, demandScore: 85, ratePremiumPct: 25 },
      { month: 6, demandScore: 88, ratePremiumPct: 28, notes: "Roland Garros" },
      { month: 7, demandScore: 92, ratePremiumPct: 32, notes: "Peak summer" },
      { month: 8, demandScore: 85, ratePremiumPct: 25 },
      { month: 9, demandScore: 82, ratePremiumPct: 22, notes: "Fashion Week" },
      { month: 10, demandScore: 75, ratePremiumPct: 15 },
      { month: 11, demandScore: 60, ratePremiumPct: 2 },
      { month: 12, demandScore: 70, ratePremiumPct: 12, notes: "Christmas markets" },
    ],
    eventApiConfig: {
      ticketmasterCity: "Paris",
      eventbriteCity: "Paris",
      customKeywords: ["Roland Garros", "Paris Fashion Week", "Bastille Day", "Christmas Market"],
    },
    regulatoryFlags: {
      hasNightCap: true,
      nightCapPerYear: 120,
      requiresLicence: true,
      licenceFieldLabel: "Numéro de déclaration",
    },
    isActive: true,
  },
  {
    marketCode: "NLD_AMS",
    displayName: "Amsterdam, Netherlands",
    country: "Netherlands",
    currency: "EUR",
    timezone: "Europe/Amsterdam",
    weekendDefinition: "fri_sat",
    flag: "🇳🇱",
    guardrailDefaults: {
      maxSingleDayChangePct: 10,
      autoApproveThreshold: 3,
      absoluteFloorMultiplier: 0.5,
      absoluteCeilingMultiplier: 2.5,
    },
    seasonalPatterns: [
      { month: 1, demandScore: 42, ratePremiumPct: -18 },
      { month: 2, demandScore: 45, ratePremiumPct: -15 },
      { month: 3, demandScore: 60, ratePremiumPct: 0 },
      { month: 4, demandScore: 88, ratePremiumPct: 30, notes: "Tulip season + King's Day" },
      { month: 5, demandScore: 80, ratePremiumPct: 20 },
      { month: 6, demandScore: 82, ratePremiumPct: 22 },
      { month: 7, demandScore: 95, ratePremiumPct: 40, notes: "Peak summer" },
      { month: 8, demandScore: 90, ratePremiumPct: 35 },
      { month: 9, demandScore: 72, ratePremiumPct: 12 },
      { month: 10, demandScore: 60, ratePremiumPct: 0 },
      { month: 11, demandScore: 48, ratePremiumPct: -12 },
      { month: 12, demandScore: 55, ratePremiumPct: -5, notes: "Sinterklaas + Christmas" },
    ],
    eventApiConfig: {
      ticketmasterCity: "Amsterdam",
      eventbriteCity: "Amsterdam",
      customKeywords: ["King's Day", "Tulip Festival", "Pride Amsterdam", "ADE"],
    },
    regulatoryFlags: {
      hasNightCap: true,
      nightCapPerYear: 30,
      requiresLicence: true,
      licenceFieldLabel: "Vergunningsnummer",
    },
    isActive: true,
  },
  {
    marketCode: "ESP_BCN",
    displayName: "Barcelona, Spain",
    country: "Spain",
    currency: "EUR",
    timezone: "Europe/Madrid",
    weekendDefinition: "fri_sat",
    flag: "🇪🇸",
    guardrailDefaults: {
      maxSingleDayChangePct: 12,
      autoApproveThreshold: 4,
      absoluteFloorMultiplier: 0.5,
      absoluteCeilingMultiplier: 2.8,
    },
    seasonalPatterns: [
      { month: 1, demandScore: 50, ratePremiumPct: -12 },
      { month: 2, demandScore: 55, ratePremiumPct: -8 },
      { month: 3, demandScore: 65, ratePremiumPct: 5, notes: "MWC Barcelona" },
      { month: 4, demandScore: 78, ratePremiumPct: 18, notes: "Easter / spring" },
      { month: 5, demandScore: 82, ratePremiumPct: 22 },
      { month: 6, demandScore: 90, ratePremiumPct: 32 },
      { month: 7, demandScore: 95, ratePremiumPct: 40, notes: "Peak summer" },
      { month: 8, demandScore: 92, ratePremiumPct: 38, notes: "Peak summer" },
      { month: 9, demandScore: 82, ratePremiumPct: 22 },
      { month: 10, demandScore: 72, ratePremiumPct: 12 },
      { month: 11, demandScore: 58, ratePremiumPct: -2 },
      { month: 12, demandScore: 62, ratePremiumPct: 5, notes: "Christmas / NYE" },
    ],
    eventApiConfig: {
      ticketmasterCity: "Barcelona",
      eventbriteCity: "Barcelona",
      customKeywords: ["MWC", "Primavera Sound", "Sonar Festival", "La Merce"],
    },
    regulatoryFlags: {
      hasNightCap: false,
      requiresLicence: true,
      licenceFieldLabel: "Número de licencia turística",
    },
    isActive: true,
  },
  {
    marketCode: "USA_MIA",
    displayName: "Miami, USA",
    country: "United States",
    currency: "USD",
    timezone: "America/New_York",
    weekendDefinition: "fri_sat",
    flag: "🇺🇸",
    guardrailDefaults: {
      maxSingleDayChangePct: 20,
      autoApproveThreshold: 7,
      absoluteFloorMultiplier: 0.5,
      absoluteCeilingMultiplier: 3.5,
    },
    seasonalPatterns: [
      { month: 1, demandScore: 92, ratePremiumPct: 35, notes: "Peak winter season" },
      { month: 2, demandScore: 90, ratePremiumPct: 32, notes: "Super Bowl season" },
      { month: 3, demandScore: 88, ratePremiumPct: 28, notes: "Spring Break" },
      { month: 4, demandScore: 75, ratePremiumPct: 15 },
      { month: 5, demandScore: 60, ratePremiumPct: 2 },
      { month: 6, demandScore: 48, ratePremiumPct: -10, notes: "Hurricane season begins" },
      { month: 7, demandScore: 45, ratePremiumPct: -15 },
      { month: 8, demandScore: 42, ratePremiumPct: -18 },
      { month: 9, demandScore: 40, ratePremiumPct: -20, notes: "Hurricane season peak" },
      { month: 10, demandScore: 58, ratePremiumPct: -5 },
      { month: 11, demandScore: 72, ratePremiumPct: 12 },
      { month: 12, demandScore: 95, ratePremiumPct: 40, notes: "Art Basel + winter peak" },
    ],
    eventApiConfig: {
      ticketmasterCity: "Miami",
      eventbriteCity: "Miami",
      customKeywords: ["Art Basel Miami", "Ultra Music Festival", "Miami Open", "South Beach Wine and Food"],
    },
    regulatoryFlags: {
      hasNightCap: false,
      requiresLicence: true,
      licenceFieldLabel: "BTR License Number",
    },
    isActive: true,
  },
  {
    marketCode: "PRT_LIS",
    displayName: "Lisbon, Portugal",
    country: "Portugal",
    currency: "EUR",
    timezone: "Europe/Lisbon",
    weekendDefinition: "fri_sat",
    flag: "🇵🇹",
    guardrailDefaults: {
      maxSingleDayChangePct: 12,
      autoApproveThreshold: 4,
      absoluteFloorMultiplier: 0.5,
      absoluteCeilingMultiplier: 2.8,
    },
    seasonalPatterns: [
      { month: 1, demandScore: 48, ratePremiumPct: -15 },
      { month: 2, demandScore: 52, ratePremiumPct: -10 },
      { month: 3, demandScore: 62, ratePremiumPct: 2 },
      { month: 4, demandScore: 75, ratePremiumPct: 15, notes: "Easter" },
      { month: 5, demandScore: 80, ratePremiumPct: 20 },
      { month: 6, demandScore: 88, ratePremiumPct: 30, notes: "Santo António festival" },
      { month: 7, demandScore: 95, ratePremiumPct: 42, notes: "Peak summer" },
      { month: 8, demandScore: 92, ratePremiumPct: 38 },
      { month: 9, demandScore: 80, ratePremiumPct: 20, notes: "Web Summit" },
      { month: 10, demandScore: 68, ratePremiumPct: 8 },
      { month: 11, demandScore: 55, ratePremiumPct: -5, notes: "Web Summit month" },
      { month: 12, demandScore: 60, ratePremiumPct: 5 },
    ],
    eventApiConfig: {
      ticketmasterCity: "Lisbon",
      eventbriteCity: "Lisbon",
      customKeywords: ["Web Summit", "NOS Alive", "Santo António", "Rock in Rio Lisboa"],
    },
    regulatoryFlags: {
      hasNightCap: false,
      requiresLicence: true,
      licenceFieldLabel: "Número AL",
    },
    isActive: true,
  },
  {
    marketCode: "USA_NSH",
    displayName: "Nashville, USA",
    country: "United States",
    currency: "USD",
    timezone: "America/Chicago",
    weekendDefinition: "fri_sat",
    flag: "🇺🇸",
    guardrailDefaults: {
      maxSingleDayChangePct: 20,
      autoApproveThreshold: 7,
      absoluteFloorMultiplier: 0.5,
      absoluteCeilingMultiplier: 4.0,
    },
    seasonalPatterns: [
      { month: 1, demandScore: 58, ratePremiumPct: 8 },
      { month: 2, demandScore: 62, ratePremiumPct: 12 },
      { month: 3, demandScore: 75, ratePremiumPct: 25, notes: "CMA Fest buildup" },
      { month: 4, demandScore: 72, ratePremiumPct: 22 },
      { month: 5, demandScore: 78, ratePremiumPct: 28 },
      { month: 6, demandScore: 92, ratePremiumPct: 42, notes: "CMA Music Festival" },
      { month: 7, demandScore: 85, ratePremiumPct: 35 },
      { month: 8, demandScore: 80, ratePremiumPct: 30 },
      { month: 9, demandScore: 75, ratePremiumPct: 25 },
      { month: 10, demandScore: 80, ratePremiumPct: 30 },
      { month: 11, demandScore: 65, ratePremiumPct: 15 },
      { month: 12, demandScore: 70, ratePremiumPct: 20, notes: "New Year's Eve" },
    ],
    eventApiConfig: {
      ticketmasterCity: "Nashville",
      eventbriteCity: "Nashville",
      customKeywords: ["CMA Fest", "Nashville Marathon", "Bonnaroo", "New Year's Eve Nashville"],
    },
    regulatoryFlags: {
      hasNightCap: false,
      requiresLicence: true,
      licenceFieldLabel: "STR Permit Number",
    },
    isActive: true,
  },
  {
    marketCode: "AUS_SYD",
    displayName: "Sydney, Australia",
    country: "Australia",
    currency: "AUD",
    timezone: "Australia/Sydney",
    weekendDefinition: "fri_sat",
    flag: "🇦🇺",
    guardrailDefaults: {
      maxSingleDayChangePct: 15,
      autoApproveThreshold: 5,
      absoluteFloorMultiplier: 0.5,
      absoluteCeilingMultiplier: 3.0,
    },
    seasonalPatterns: [
      { month: 1, demandScore: 90, ratePremiumPct: 30, notes: "Southern hemisphere summer" },
      { month: 2, demandScore: 85, ratePremiumPct: 25 },
      { month: 3, demandScore: 72, ratePremiumPct: 12 },
      { month: 4, demandScore: 60, ratePremiumPct: 0, notes: "Autumn / Easter" },
      { month: 5, demandScore: 50, ratePremiumPct: -10 },
      { month: 6, demandScore: 45, ratePremiumPct: -15 },
      { month: 7, demandScore: 55, ratePremiumPct: -5, notes: "School holidays" },
      { month: 8, demandScore: 52, ratePremiumPct: -8 },
      { month: 9, demandScore: 65, ratePremiumPct: 5, notes: "Spring begins" },
      { month: 10, demandScore: 75, ratePremiumPct: 15 },
      { month: 11, demandScore: 82, ratePremiumPct: 22 },
      { month: 12, demandScore: 95, ratePremiumPct: 38, notes: "Summer + NYE Harbour" },
    ],
    eventApiConfig: {
      ticketmasterCity: "Sydney",
      eventbriteCity: "Sydney",
      customKeywords: ["NYE Sydney Harbour", "Sydney Festival", "Mardi Gras", "Vivid Sydney"],
    },
    regulatoryFlags: {
      hasNightCap: false,
      requiresLicence: false,
    },
    isActive: true,
  },
];
