export const SOURCES_SEED = [
  {
    sourceId: "hostaway",
    name: "Hostaway Sync",
    description: "Syncs listings, calendar availability, and reservations from Hostaway PMS. Read-only — never writes back to Hostaway.",
    iconName: "Database",
    schedule: "0 */4 * * *",
    scheduleLabel: "Every 4 hours",
    isEnabled: true,
    lastRunStatus: "idle",
    config: {
      calendarDays: 90,
      includeBlockedDays: true,
    },
  },
  {
    sourceId: "competitors",
    name: "Competitor Rates",
    description: "Fetches comparable listing rates from Airbnb and Booking.com for market benchmarking.",
    iconName: "BarChart2",
    schedule: "0 */6 * * *",
    scheduleLabel: "Every 6 hours",
    isEnabled: true,
    lastRunStatus: "idle",
    config: {
      radiusKm: 2,
      maxComps: 20,
      bedroomMatch: true,
    },
  },
  {
    sourceId: "events",
    name: "Event Intelligence",
    description: "Monitors local event calendars for demand signals. Uses Ticketmaster and Eventbrite APIs when configured; falls back to AI-generated event data.",
    iconName: "Calendar",
    schedule: "0 */12 * * *",
    scheduleLabel: "Every 12 hours",
    isEnabled: true,
    lastRunStatus: "idle",
    config: {
      lookAheadDays: 60,
      minImpactLevel: "low",
    },
  },
  {
    sourceId: "seasonality",
    name: "Seasonality Patterns",
    description: "Loads monthly demand benchmarks from the market template for the current organization's market.",
    iconName: "TrendingUp",
    schedule: "0 0 * * *",
    scheduleLabel: "Daily",
    isEnabled: true,
    lastRunStatus: "idle",
    config: {},
  },
];

export const DETECTORS_SEED = [
  {
    detectorId: "booking_pace",
    name: "Booking Pace",
    category: "BOOKING_PACE",
    triggerSource: "hostaway",
    description: "Detects when booking pace deviates from the 30-day baseline, signaling under/over-pricing.",
    isEnabled: true,
    lastSignalsFound: 0,
    config: {
      baselineDays: 30,
      thresholdPct: 20,
      lookAheadDays: 14,
    },
  },
  {
    detectorId: "lead_time",
    name: "Lead Time Shift",
    category: "LEAD_TIME",
    triggerSource: "hostaway",
    description: "Detects shifts in average booking lead time, indicating changes in guest booking behavior.",
    isEnabled: true,
    lastSignalsFound: 0,
    config: {
      baselineDays: 60,
      shiftThresholdDays: 3,
    },
  },
  {
    detectorId: "cancellation_rate",
    name: "Cancellation Rate",
    category: "CANCELLATION_RISK",
    triggerSource: "hostaway",
    description: "Flags elevated cancellation rates compared to market average, indicating pricing or policy issues.",
    isEnabled: true,
    lastSignalsFound: 0,
    config: {
      windowDays: 30,
      marketAvgPct: 5,
      alertThresholdPct: 8,
    },
  },
  {
    detectorId: "occupancy",
    name: "Occupancy Rate",
    category: "OCCUPANCY",
    triggerSource: "hostaway",
    description: "Monitors rolling occupancy rate and alerts when significantly above or below target.",
    isEnabled: true,
    lastSignalsFound: 0,
    config: {
      targetOccupancyPct: 75,
      lookAheadDays: 30,
      overThresholdPct: 90,
      underThresholdPct: 60,
    },
  },
  {
    detectorId: "gap_analysis",
    name: "Gap Analysis",
    category: "GAP_FILL",
    triggerSource: "hostaway",
    description: "Finds 1-4 night gaps between confirmed reservations that could be filled with discount pricing.",
    isEnabled: true,
    lastSignalsFound: 0,
    config: {
      maxGapNights: 4,
      lookAheadDays: 60,
    },
  },
  {
    detectorId: "length_of_stay",
    name: "Length of Stay",
    category: "LOS_OPTIMIZATION",
    triggerSource: "hostaway",
    description: "Analyzes booking length patterns and suggests minimum stay adjustments to maximize revenue.",
    isEnabled: true,
    lastSignalsFound: 0,
    config: {
      analysisWindowDays: 90,
    },
  },
  {
    detectorId: "competitor_rate",
    name: "Competitor Rate Delta",
    category: "COMPETITOR_RATE",
    triggerSource: "competitors",
    description: "Detects significant price gaps between your rates and comparable listings in the market.",
    isEnabled: true,
    lastSignalsFound: 0,
    config: {
      deltaThresholdPct: 10,
      useP50: true,
    },
  },
  {
    detectorId: "day_of_week",
    name: "Day-of-Week Pattern",
    category: "DAY_OF_WEEK",
    triggerSource: "hostaway",
    description: "Identifies consistent day-of-week pricing opportunities based on historical booking patterns.",
    isEnabled: true,
    lastSignalsFound: 0,
    config: {
      analysisWindowWeeks: 12,
      minOccurrences: 6,
    },
  },
  {
    detectorId: "review_score",
    name: "Review Score Trend",
    category: "REVIEW_SCORE",
    triggerSource: "hostaway",
    description: "Monitors review score trends and recommends pricing adjustments based on reputation signals.",
    isEnabled: true,
    lastSignalsFound: 0,
    config: {
      windowReviews: 20,
      alertDropPts: 0.3,
    },
  },
  {
    detectorId: "event_impact",
    name: "Event Impact",
    category: "EVENT_IMPACT",
    triggerSource: "events",
    description: "Calculates expected demand uplift from upcoming events and recommends preemptive rate increases.",
    isEnabled: true,
    lastSignalsFound: 0,
    config: {
      lookAheadDays: 60,
      minImpactLevel: "medium",
    },
  },
  {
    detectorId: "seasonality_detector",
    name: "Seasonality Drift",
    category: "SEASONAL_SHIFT",
    triggerSource: "seasonality",
    description: "Detects when current pricing diverges from expected seasonal benchmarks in the market template.",
    isEnabled: true,
    lastSignalsFound: 0,
    config: {
      driftThresholdPct: 10,
    },
  },
  {
    detectorId: "channel_mix",
    name: "Channel Mix",
    category: "CHANNEL_MIX",
    triggerSource: "hostaway",
    description: "Analyzes booking channel distribution and flags over-reliance on a single OTA.",
    isEnabled: false,
    lastSignalsFound: 0,
    config: {
      overRelianceThresholdPct: 70,
    },
  },
];
